port: 8580 # prot of the local http server

cache: 
  active: false # to activate the cache set this to true
  path: ./cache  # folder to the cache, relativ or absolute
  maxage: 2160 # max age of the tiles in hours, 90 days = 2160, will be automatically deleted

logging:
  level: info # logging only info messages, for more switch to debug, only errors, error would be aproriate
  filename: # set some filename wil activate an automatic file logger
  gelf-url: # using some kind of gelf compatible server (as graylog) you can set here url of the server
  gelf-port: # port of the gelf server

provider: # here starts the tileserver parts
  gebco: # one wms server section, will be availble with http://localhost:8580/gebco/tms/{z}/{x}/{y}.png
    url: https://geoserver.openseamap.org/geoserver/gwc/service/wms  # the server to use
    type: wms # which type of server (tms, wms, xyz)
    layers: gebco2021:gebco_2021 # the layers (for wms)
    format: image/png # normally the tiles are in png format, format conversion will not be done
    nocache: false
    headers: # here you can set additional headers, if the server (like osm) requires some special headers
      Accept: image/png,image/jpg,*/*;q=0.8
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:143.0) Gecko/20100101 Firefox/143.0
